#!/bin/sh
. "$(dirname "$0")/_/husky.sh"


# Get the list of staged files
staged_files=$(git diff --cached --name-only)

# Check if any file is in the web directory
if echo "$staged_files" | grep -q "^web/"; then
  # Run type-check for web
  cd web
  yarn tsc
  cd ..
fi

# Check if any file is in the contracts directory
if echo "$staged_files" | grep -q "^contracts/"; then
  # Run type-check for contracts
  cd contracts
  yarn tsc
  cd ..
fi

yarn lint-staged
